server:
  port: 16012

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 18763
        dashboard: 127.0.0.1:8748
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
    service:
      name: provider


test:
  config:
    refresh: false


swagger:
    enable: true