server:
  port: 15013

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 18763
        dashboard: 127.0.0.1:8748

feign:
  sentinel:
    enabled: true


test:
  config:
    refresh: false

swagger:
    enable: true